site_name: Polyscope Doc
theme: 
  name: readthedocs
docs_dir: docs
nav:
  - Home: index.md
  - Pages: pages.md
  - Tutorial 1 (Basics): tutorial_basics.md
  - Tutorial 2 (Annotating): tutorial_polyzoomer.md
  - Tutorial 3 (Multizoomer): tutorial_multizoomer.md