name: Build and Deploy MkDocs site to /src/docs

on:
  push:
    branches:
      - main
      - release/*
    paths:
      - 'docs/**' 

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install MkDocs and dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mkdocs mkdocs-material

    - name: Build MkDocs site
      run: mkdocs build --clean --site-dir ./src/polyscope-main/docs

    - name: Commit and Push Changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add src/polyscope-main/docs/
        if [ -n "$(git status --porcelain)" ]; then
          git commit -m "Deploy MkDocs site to src/polyscope-main/docs"
          git push origin ${{ github.ref }}
        else
          echo "No changes to commit"
        fi
