name: Test GHCR Push

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Create a small test image
      run: |
        echo -e "FROM alpine\nCMD [\"echo\", \"Hello, World!\"]" > Dockerfile

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag test-image:latest

    - name: Convert repository owner name to lowercase
      id: convert-owner-name
      run: echo "owner=$(echo ${{ github.repository_owner }} | awk '{print tolower($0)}')" >> $GITHUB_ENV

    - name: Tag the Docker image for GitHub Packages
      run: docker tag test-image:latest ghcr.io/${{ env.owner }}/test-image:latest

    - name: Push the Docker image to GitHub Packages
      run: docker push ghcr.io/${{ env.owner }}/test-image:latest
      
